{
  "version": 0.3,
  "lastModified": 1726088850033,
  "lastModifiedIso": "2024-09-11T21:07:30.033Z",
  "classFilename": "../../node_modules/@qooxdoo/framework/source/class/qx/core/AssertionError.js",
  "type": "bootstrap",
  "location": {
    "start": {
      "line": 23,
      "column": 0,
      "index": 568
    },
    "end": {
      "line": 59,
      "column": 3,
      "index": 1553
    }
  },
  "className": "qx.core.AssertionError",
  "jsdoc": {
    "raw": [
      "*",
      " * Assertion errors are thrown if an assertion in {@link qx.core.Assert}",
      " * fails.",
      " "
    ],
    "@description": [
      {
        "name": "@description",
        "body": "<p>Assertion errors are thrown if an assertion in {@link qx.core.Assert}\n fails.</p>"
      }
    ]
  },
  "superClass": "qx.type.BaseError",
  "construct": {
    "type": "function",
    "params": [
      {
        "name": "comment"
      },
      {
        "name": "failMessage"
      }
    ],
    "location": {
      "start": {
        "line": 36,
        "column": 2,
        "index": 986
      },
      "end": {
        "line": 39,
        "column": 3,
        "index": 1133
      }
    }
  },
  "members": {
    "__trace": {
      "jsdoc": null,
      "access": "private",
      "location": {
        "start": {
          "line": 48,
          "column": 4,
          "index": 1337
        },
        "end": {
          "line": 48,
          "column": 17,
          "index": 1350
        }
      },
      "appearsIn": []
    },
    "getStackTrace": {
      "jsdoc": {
        "raw": [
          "*",
          "     * Stack trace of the error",
          "     *",
          "     * @return {String[]} The stack trace of the location the exception was thrown",
          "     "
        ],
        "@description": [
          {
            "name": "@description",
            "body": "<p>Stack trace of the error</p>"
          }
        ],
        "@return": [
          {
            "name": "@return",
            "body": "{String[]} The stack trace of the location the exception was thrown",
            "type": "String[]",
            "description": "The stack trace of the location the exception was thrown"
          }
        ]
      },
      "access": "public",
      "location": {
        "start": {
          "line": 55,
          "column": 4,
          "index": 1495
        },
        "end": {
          "line": 57,
          "column": 5,
          "index": 1545
        }
      },
      "type": "function",
      "params": [],
      "returnType": {
        "type": "String[]"
      },
      "appearsIn": []
    }
  },
  "statics": {},
  "properties": {}
}