{
  "className": "qx.io.exception.Exception",
  "packageName": "qx.io.exception",
  "name": "Exception",
  "superClass": "qx.type.BaseError",
  "interfaces": [],
  "mixins": [],
  "functionName": null,
  "clazz": {
    "location": {
      "start": {
        "line": 22,
        "column": 0,
        "index": 543
      },
      "end": {
        "line": 37,
        "column": 3,
        "index": 872
      }
    },
    "jsdoc": {
      "@description": [
        {
          "name": "@description",
          "body": "<p>A generic class for representing exceptions that occur during io operations.</p>"
        }
      ]
    }
  },
  "type": "class",
  "construct": {
    "location": {
      "start": {
        "line": 31,
        "column": 2,
        "index": 732
      },
      "end": {
        "line": 36,
        "column": 3,
        "index": 868
      }
    },
    "jsdoc": {
      "@description": [
        {
          "name": "@description",
          "body": "<p>Constructor</p>"
        }
      ],
      "@param": [
        {
          "name": "@param",
          "body": "message {String}"
        },
        {
          "name": "@param",
          "body": "code {Number}"
        },
        {
          "name": "@param",
          "body": "data {*|null}"
        }
      ]
    }
  },
  "descendants": [
    "qx.io.exception.Cancel",
    "qx.io.exception.Protocol",
    "qx.io.exception.Transport"
  ]
}