{
  "className": "qx.type.BaseError",
  "packageName": "qx.type",
  "name": "BaseError",
  "superClass": "Error",
  "interfaces": [],
  "mixins": [],
  "functionName": null,
  "clazz": {
    "location": {
      "start": {
        "line": 20,
        "column": 0,
        "index": 730
      },
      "end": {
        "line": 88,
        "column": 3,
        "index": 2540
      }
    },
    "jsdoc": {
      "@description": [
        {
          "name": "@description",
          "body": "<p>This class is the common super class for all error classes in qooxdoo.\n It has a comment and a fail message as members. The toString method returns\n the comment and the fail message separated by a colon.</p>"
        }
      ]
    }
  },
  "type": "class",
  "construct": {
    "location": {
      "start": {
        "line": 33,
        "column": 2,
        "index": 1131
      },
      "end": {
        "line": 46,
        "column": 3,
        "index": 1598
      }
    },
    "jsdoc": {
      "@description": [
        {
          "name": "@description",
          "body": ""
        }
      ],
      "@param": [
        {
          "name": "@param",
          "body": "comment {String} Comment passed to the assertion call",
          "paramName": "comment",
          "description": " Comment passed to the assertion call",
          "type": "String"
        },
        {
          "name": "@param",
          "body": "failMessage {String} Fail message provided by the assertion",
          "paramName": "failMessage",
          "description": " Fail message provided by the assertion",
          "type": "String"
        }
      ]
    }
  },
  "statics": {
    "DEFAULTMESSAGE": {
      "location": {
        "start": {
          "line": 54,
          "column": 4,
          "index": 1801
        },
        "end": {
          "line": 54,
          "column": 27,
          "index": 1824
        }
      },
      "type": "variable",
      "access": "public"
    }
  },
  "members": {
    "__sTrace": {
      "location": {
        "start": {
          "line": 64,
          "column": 4,
          "index": 2032
        },
        "end": {
          "line": 64,
          "column": 18,
          "index": 2046
        }
      },
      "type": "variable",
      "access": "private"
    },
    "__comment": {
      "location": {
        "start": {
          "line": 65,
          "column": 4,
          "index": 2052
        },
        "end": {
          "line": 65,
          "column": 19,
          "index": 2067
        }
      },
      "type": "variable",
      "access": "private"
    },
    "message": {
      "location": {
        "start": {
          "line": 68,
          "column": 4,
          "index": 2139
        },
        "end": {
          "line": 68,
          "column": 17,
          "index": 2152
        }
      },
      "jsdoc": {
        "@description": [
          {
            "name": "@description",
            "body": ""
          }
        ],
        "@type": [
          {
            "name": "@type",
            "body": "{String} Fail message provided by the assertion"
          }
        ]
      },
      "type": "variable",
      "access": "public"
    },
    "getComment": {
      "location": {
        "start": {
          "line": 75,
          "column": 4,
          "index": 2291
        },
        "end": {
          "line": 77,
          "column": 5,
          "index": 2340
        }
      },
      "jsdoc": {
        "@description": [
          {
            "name": "@description",
            "body": "<p>Comment passed to the assertion call</p>"
          }
        ],
        "@return": [
          {
            "name": "@return",
            "body": "{String} The comment passed to the assertion call",
            "type": "String",
            "description": " The comment passed to the assertion call"
          }
        ]
      },
      "type": "function",
      "access": "public"
    }
  },
  "descendants": [
    "qx.core.AssertionError",
    "qx.core.ValidationError",
    "qx.io.exception.Exception"
  ]
}